version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # 호스트의 8080 포트를 컨테이너의 8080 포트에 연결
    environment:
      SPRING_PROFILES_ACTIVE: prod # 프로파일 설정
